version: '2'
services:
    jhipstersampleonlineapplication-app:
        image: jhipstersampleonlineapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleonlineapplication-mysql:3306/jhipstersampleonlineapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleonlineapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleonlineapplication-mysql
